apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: fathyafi/fe-app-gke:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "256Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
            # initialDelaySeconds: 5
            # periodSeconds: 10